version: '3'

services:
  orcl:
    hostname: orcl
    image: container-registry.oracle.com/database/enterprise:12.2.0.1
    ports:
      - "1521:1521"
      - "5500:5500"
    container_name: orcl
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - oradata:/ORCL:rw
volumes:
  oradata: