version: '3'

services:
  centos7:
    hostname: centos7
    build: ./centos7
    image: centos7:1.0
    # image: centos
    container_name: centos7
    ports:
     - "2222:22"
    privileged: true
    #command: /sbin/init
